---
title: "エコノミストのためのR"
author: "服部直樹"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
page-footer: "Copyright 2023, Naoki Hattori"
output: 
  bookdown::gitbook:
    split_by: rmd
    df_print: "paged"
    highlight: default
    toc_depth: 3    
    config:
      toc:
        collapse: section
        scroll_highlights: yes
        before: |
          <li><a href="https://econ-code.verse.jp/index.html">エコノミストのためのR</a></li>
        after: |
          <li><a href="https://github.com/rstudio/bookdown">Published with bookdown</a></li>
      toolbar:
        position: fixed
      edit: null
      download: false
      sharing:
        github: yes
        facebook: yes
        linkedin: yes
        twitter: yes
github-repo: "naohat23/econ-code-bookdown"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# はじめに

本書は、エコノミストがRを使用して経済・金融データ分析を行うための方法をまとめたものです。

Rによるプログラミング、データ分析、計量経済学について解説した書籍は、世の中に沢山あります。しかし、エコノミストがよく使用するコードや分析方法を体系的に整理し、いつでも・どこからでもコードにアクセスできるようにしたサービスはまだ無かったので、本書を作成しました。

なお、本書のソースコードは[GitHubリポジトリ](https://github.com/naohat23/econ-code-bookdown)で管理しています。改善点があれば、イシューやプルリクエストでお知らせいただければ幸いです。

## なぜRを使うのか？

データ分析を行うことができるソフトウェアは、R以外にも、EViews、Stata、Pythonといった選択肢があります。では、なぜRを使用するのでしょうか。

**無料**：　Rは無料で使用することができます。オフィスでも、自宅でも、所属組織が変わっても同じソフトウェアを使って作業することができるため、わざわざ違うソフトウェアの使用方法を新たに覚える必要がありません。また、無料で誰でも使えるということは、世界中に多くのユーザーがいて、書籍やオンラインに情報が沢山あるということでもあります。本書もその一つです。

**豊富なパッケージ**：　Rはデータ分析を行うための追加パッケージが大量に開発されており、用途に応じてパッケージをインストールすることで、様々なデータ分析手法を使用することが可能です。オーソドックスな計量経済分析はもちろん、機械学習、自然言語処理、地理データ分析など、Rで実施可能な分析は多岐にわたります。

**データ分析に特化**：　RとPythonはよく比較されますが、Pythonが汎用プログラミング言語である一方、Rはデータ分析に特化しているという違いがあります。特に、Rの統合開発環境であるRStudioは、コードの記述と実行に加え、変数の内容を一覧表示したり、グラフをプロットしたり、ディレクトリやヘルプを表示したり、といった分析を補助する機能を一つの画面で操作することができ、ストレスなく作業できます。データ分析を行うのであれば、まずRを選択すべきでしょう。一方、高度な深層学習を行ったり、分析した結果を用いてアプリケーションを作成したりするのであれば、Pythonが向いているといえます。

**直感的なデータ操作**：　Rのパッケージの一つである`tidyverse`では、直感的かつ効率的なデータ操作（データハンドリング）を行うことができます。データセットを読み込んだ後、変数の選択、フィルタ、集計、結合、新たな変数の計算、異常値の処理といった前処理をシームレスに実施し、そのまま図表作成や分析に進むことができます。また、データセットの読み込みも、読み込み元がローカルかウェブかを問わず容易に行うことができます。

**強力なグラフ作成機能**：　Rの`ggplot2`パッケージは強力なグラフ作成機能をもち、折れ線グラフ、棒グラフ、散布図といったおなじみのグラフだけでなく、ヒートマップ、QQプロット、ステップグラフ、ドットプロット、箱ひげ図、ヴァイオリングラフ、ジッターグラフ、複合グラフ（ファセット）などの高度なグラフを作成することができます。グラフは日本語表記にも対応しており、フォーマットを設定すれば、そのままレポートにも使用可能です。

## 本書でできること

本書では、エコノミストがRを使用してデータ分析を行う方法を順序だてて学ぶことができます。

Rの設定、Rの演算やオブジェクトの取り扱い方といった基本的な使用方法、`tidyverse`パッケージを使ってデータを自由に操作する方法、季節調整やトレンドなどの時系列データ特有の処理、`ggplot2`パッケージを使ったグラフ作成、データの分析方針を立てるための探索的データ分析（EDA）、計量経済学の基礎である線形単回帰・重回帰、時系列データの操作方法や分析方法について解説しています。すべてRのコードを記載していますので、自分の環境で結果を再現することが可能です。

一方、本書はデータ分析の手法とコードの解説を主な目的にしているため、厳密な数学的解説は行っていません。手法の背景にある数学的解説が必要な場合は、参考文献を参照してください。また、データ分析の手法について、エコノミストが日常業務で使用することが比較的少ない機械学習、深層学習、自然言語処理の手法は、現時点では取り上げていません。

## 目次

### 第1章 はじめに {.unnumbered}

本書の問題意識や対象範囲、目次、参考文献・ウェブサイト、変更履歴を記載しています。

### 第2章 Rの設定 {.unnumbered}

Rを使用するにあたり、まず必要な環境構築を行います。

RとRStudioのインストール、バージョン確認、Rの機能を拡張するパッケージのインストールとインポート、グラフ作成の事前設定に加え、本書で使用するサンプルデータセットを紹介します。

また、オフィスや大学などのプロキシ環境下でRを使用する際に必要な通信設定についても解説します。

### 第3章 Rの基本的な使用方法 {.unnumbered}

Rで作業を始める前に、プログラミング言語としてのRの基本的な使用方法を簡単に紹介します。

プログラムの実行方法、ショートカットキー、演算方法、ベクトル・行列・データフレーム・リスト、文字列といった各種データの取り扱い方法、`if`文や`for`ループなどの制御構文、データの読み込み・書き出し方法、オブジェクトのセーブ・ロード方法について解説します。

この章をまず一読したうえで次章以降へ進み、後から必要に応じてリファレンス的に使用するのが良いでしょう。

### 第4章 tidyverseによるデータ操作 {.unnumbered}

Rで直感的なデータ操作用を行うパッケージである`tidyverse`の使用方法を紹介します。

変数選択や各種条件によるフィルタ、並べ替えなどの基本的な操作に加え、新たな変数の作成、集計、重複処理、欠損値処理、補完処理、サンプリング、縦型・横型の変換といったデータ前処理の手法についても解説します。

読み込んだデータを分析に「使える」ようにするために必須の内容です。

### 第5章 ggplot2によるグラフ作成 {.unnumbered}

`ggplot2`パッケージを主に使用したグラフ作成方法を紹介します。

最初に、GUI形式でどのようなグラフを作成するか検討する方法を紹介したうえで、`ggplot2`によるコード記述形式のグラフ作成方法を解説します。

取り上げるグラフは、1次元・2次元の度数分布、密度グラフ、ヒストグラム、QQプロット、散布図、バブルチャート、棒グラフ、円グラフ、折れ線グラフ、ステップグラフ、面グラフ、箱ひげ図（ボックスプロット）、ヴァイオリングラフ、ジッターグラフ、ドットプロット、複合グラフ（ファセット）など、多岐にわたります。

また、散布図や折れ線グラフに系列名などのテキストアノテーションを行う方法、グラフの見栄えを整える上で欠かせない色、軸、凡例、フォントなどの設定方法についても紹介しています。

### 第6章 探索的データ分析（EDA） {.unnumbered}

本格的なデータ分析の方針を立てるために必要な、探索的データ分析（EDA）の方法を紹介します。

具体的には、データの中身や分布、変数間の関係性・相関を一括して確認する方法について解説します。EDAは軽視されがちですが、極めて重要なプロセスであり、データ分析の成否はEDAが決めるといっても過言ではありません。

### 第7章 線形回帰 {.unnumbered}

計量経済分析の最も基本的な手法である線形回帰の内容と、Rによる実行方法を紹介します。

まず、前提として、統計学・計量経済学で使用される基本的な用語を説明します。次に、線形回帰の推定方法である最小2乗法と、統計的仮説検定について解説したうえで、実務で頻繁に用いる水準モデル、対数モデル、変化率モデル、多項式モデル、交互作用モデル、ダミー変数モデルについて、それぞれの内容と係数の解釈方法を説明します。

この部分は、なるべく直感的に理解できるような説明を心がけました。最後に、それらのモデルをRで推定する方法を、西山 他（2019）の実例を解く形で紹介します。

### 第8章 時系列データ操作 {.unnumbered}

経済・金融分析に欠かせない時系列データの操作方法を紹介します。

時系列データ用のts形式に特有の操作、日付型データ関数、ラグ・リード系列や変化率系列の計算方法、頻度変換、季節調整（X13、STL分解）、トレンド（線形トレンド、区分線形トレンド、HPフィルタ、一般化加法モデル）、構造変化などのトピックを取り上げています。

### 第9章 時系列分析 {.unnumbered}

時系列データを用いた基本的な分析手法である、ボックス＝ジェンキンス法とVARモデルを紹介します。

時系列分析を行う上で必須の定常性、単位根、系列相関、共和分の概念と検定方法を解説し、それらを用いた分析手法として、ARMA・ARIMAモデルなどの1変数時系列モデルであるボックス＝ジェンキンス法と、多変数時系列モデルであるVARモデルを紹介します。

時系列分析はエコノミストが経済・金融分析を行う上で欠かせないツールであり、本書では、単位根検定や共和分検定のシステマチックな検定フロー、構造VAR・VECモデル、一般化インパルス応答など、入門・中級のテキストが十分カバーしていないテーマを取り扱っています。

### 付録 寄与度の計算方法 {.unnumbered}

経済・金融指標の分析で頻繁に使用する、寄与度分解の計算方法をまとめています。

指標の構成タイプによって、和・差の指標、積の指標、商の指標、固定加重平均の指標、可変加重平均の指標に分け、それぞれの指標の変動要因を構成項目別に分解する公式を示したうえで、実例としてGDP、経常利益、失業率、ラスパイレス指数、現金給与総額などを寄与度分解する計算方法を紹介しています。

### パネルデータ分析 {.unnumbered}

現在作成中です。

## 参考文献・ウェブサイト

### Rプログラミング {.unnumbered}

#### 入門・初級 {.unnumbered}

-   [馬場真哉（2020）『R言語ではじめるプログラミングとデータ分析』ソシム株式会社](https://www.socym.co.jp/book/1238)

-   [松村優哉、湯谷啓明、紀ノ定保礼、前田和寛（2021）『改訂2版 Rユーザのための RStudio［実践］入門ーtidyverseによるモダンな分析フローの世界ー』技術評論社](https://gihyo.jp/book/2021/978-4-297-12170-9)

#### 中級 {.unnumbered}

-   [ハドリー・ウィッカム、ギャレット・グロールマンド（2017）『Rではじめるデータサイエンス』オライリー・ジャパン](https://www.oreilly.co.jp/books/9784873118147/)

    ウィッカム、グロールマンド（2017）の原著版 "R for Data Science"は、[こちらのウェブサイト](https://r4ds.had.co.nz/index.html)で全文閲覧できます。

-   [松村優哉、瓜生真也、吉村広志（2022）『Rユーザのためのtidymodels［実践］入門ーモダンな統計・機械学習モデリングの世界ー』技術評論社](https://gihyo.jp/book/2023/978-4-297-13236-1)

### 統計学・計量経済学 {.unnumbered}

#### 入門・初級 {.unnumbered}

-   [山本勲（2015）『実証分析のための計量経済学ー正しい手法と結果の読み方ー』中央経済社](https://www.biz-book.jp/isbn/978-4-502-16811-6)

#### 中級 {.unnumbered}

-   [Hanck, C., Arnold, M., Gerber, A., and Schmelzer, M., (2021) "Introduction to Econometrics with R"](https://www.econometrics-with-r.org/index.html)

-   [仲嶋亮（2020）「「誘導型推定」v.s.「構造型推定」」 経済セミナー編集部 編『新版 進化する経済学の実証分析』日本評論社](https://www.nippyo.co.jp/shop/book/8321.html)

-   [西山慶彦、新谷元嗣、川口大司、奥井亮（2019）『計量経済学』有斐閣](http://www.yuhikaku.co.jp/books/detail/9784641053854)

    西山 他（2019）の実証例のRコードは、[北川梨津（2020）「西山 他『計量経済学』のためのR」](https://ritsu1997.github.io/r-for-nlas-econometrics/)が提供しています。

-   [星野匡郎、田中久稔、北川梨津（2023）『Rによる実証分析（第2版）ー回帰分析から因果関係へー』オーム社](https://www.ohmsha.co.jp/book/9784274230028/)

-   [マクリン謙一郎（2022）「再現性問題における統計学の役割と責任」日本評論社『経済セミナー』2022年6・7月号　通巻 726号](https://www.nippyo.co.jp/shop/magazine/8801.html)

-   [山澤成康（2004）『実戦 計量経済学入門』日本評論社](https://www.nippyo.co.jp/shop/book/2297.html)

#### 上級 {.unnumbered}

-   [北岡孝義、高橋青天、溜川健一、矢野順治（2013）『EViewsで学ぶ実証分析の方法』日本評論社](https://www.nippyo.co.jp/shop/book/6394.html)

-   [末石直也（2015）『計量経済学ーミクロデータ分析へのいざないー』日本評論社](https://www.nippyo.co.jp/shop/book/6899.html)

### 時系列データ分析 {.unnumbered}

#### 入門・初級 {.unnumbered}

-   [熊本方雄（2022）「金融時系列データ分析を用いた論文の書き方」 経済セミナー編集部 編『経済論文の書き方』日本評論社 第9章](https://www.nippyo.co.jp/shop/book/8883.html)

-   [横内大介、青木義充（2014）『時系列データ分析』技術評論社](https://gihyo.jp/book/2014/978-4-7741-6301-7)

#### 中級 {.unnumbered}

-   [Hyndman, R.J., and Athanasopoulos, G. (2018) "Forecasting: principles and practice, 2nd edition", OTexts: Melbourne, Australia.](https://otexts.com/fpp2/)

-   [アイリーン・ニールセン（2021）『実践 時系列解析ー統計と機械学習による予測ー』オライリー・ジャパン](https://www.oreilly.co.jp/books/9784873119601/)

-   [Sax, C., and Eddelbuettel, D., (2018) "Seasonal Adjustment by X-13ARIMA-SEATS in R"](https://cran.r-project.org/web/packages/seasonal/vignettes/seas.pdf)

-   [奥本佳伸（2016）「季節調整法プログラム センサス局法X-13ARIMA-SEATSを日本のいくつかの経済統計データに適用した結果とその検討」千葉大学『経済研究』第30巻第4号](https://opac.ll.chiba-u.jp/da/curator/900119389/09127216_30_4_1-42.pdf)

-   [馬場真哉（2018）『時系列分析と状態空間モデルの基礎ーRとStanで学ぶ理論と実装ー』プレアデス出版](http://www.pleiades-publishing.co.jp/pdf/pdf08.html)

-   [肥後雅博、中田（黒田）祥子（1998）「経済変数から基調的変動を抽出する時系列手法について」日本銀行金融研究所『金融研究』1998.12](https://www.imes.boj.or.jp/research/papers/japanese/kk17-6-2.pdf)

#### 上級 {.unnumbered}

-   [ウォルター・エンダース（2019）『実証のための計量時系列分析（原著第4版）』有斐閣](https://www.yuhikaku.co.jp/books/detail/9784641165489)

    訳者の新谷元嗣、藪友良による[本書日本語版のサポートページ](https://www.fbc.keio.ac.jp/~tyabu/enders/)には、練習問題の解答例、データのExcelファイルに加えて、EViewsを用いて教科書の内容を再現するための資料が掲載されています。また、Rのコードは[David Gabauerのウェブサイト](https://sites.google.com/view/davidgabauer/use-rpython)で提供されています。

-   [宮尾龍蔵（2006）『マクロ金融政策の時系列分析ー政策効果の理論と実証ー』日本経済新聞出版](https://bookplus.nikkei.com/atcl/catalog/2006/9784532133153/)

-   [村尾博（2019）『Rで学ぶVAR実証分析ー時系列分析の基礎から予測までー』オーム社](https://www.ohmsha.co.jp/book/9784274224775/)

    村尾（2019）の内容のエッセンスやRコードは[村尾氏個人のウェブサイト](http://www43.tok2.com/home/kyotowalk/study_room.html)で閲覧することができます。まずはウェブサイトを確認してから書籍を購入することをおすすめします。

## 変更履歴

### 2025年3月17日 マイナーアップデート{-}
-   第2章「Rの設定」の「通信関連の設定」に`httr`パッケージを使用した外部通信確認用のコードを追加。また、「パッケージ」と「R起動時に実行する設定」に`httr`パッケージを追加。「R起動時に実行する設定」でSSL設定のコードが重複していた点を修正。
-   付録「寄与度の計算方法」の「商の指標」で、「実例：失業率」の最後の式の誤差項の整理方法を変更。

### 2024年12月28日 マイナーアップデート {-}

-   第8章「時系列データ操作」の一部で、OWIDのCOVID-19データセットにおける重複行の存在によりエラーが発生。`dplyr::distinct()`関数を挿入して重複行を削除し、エラーを修正。
-   付録「寄与度の計算方法」の「商の指標」で、「実例：失業率」の最後の式の符号が誤っていた点を修正。

### 2023年12月13日 マイナーアップデート {-}

-   第2章から第9章の各Rmdファイル名の先頭に02〜09の連番を付与し、ファイル名を変更
-   第1章「はじめに」の「参考文献」に、星野 他（2023）と山澤（2004）を追加。
-   第2章「Rの設定」の「パッケージ」に、`broom`、`fixest`、`summarytools`パッケージを追加したほか、既存の各パッケージのリンク先ウェブサイトを各パッケージ指定の公式ウェブサイトに変更。また、「パッケージ」の「インストール時のエラー」に`summarytools`パッケージのエラー（MacのRでXQuartzが必要になる事象）に関する記述を追加。
-   第3章「Rの基本的な使用方法」の「文字列操作」で、「文字列の検出・置換」を「検出」と「置換」に分割。
-   第3章「Rの基本的な使用方法」の「データの書き出し」で、`write.csv()`関数の`na`引数に関する記述を追加。
-   第4章「tidyverseによるデータ操作」の「列名の変更」で、サンプルデータセットを`data_owid`から`iris`に変更した上で、「複数列名の一括変更」に関する記述を追加。
-   第6章「探索的データ分析」の「データの中身」に、`str()`関数に関する記述、`summary()`関数の`maxsum`引数に関する記述、`summary()`関数の結果をウィンドウに出力する方法、`summarytools`パッケージに関する記述を追加した上で、各関数・パッケージ別に小見出しを分割。
-   第7章「線形回帰」の「最小2乗法（OLS）」で、最小2乗法の仮定1〜3に線形性の仮定を追加し、仮定1〜4に修正。また、線形性以外の各仮定の説明を補足し、各仮定について記述した参考文献を追加。
-   第7章「線形回帰」の「Rの重回帰モデル推定」で、「実例：線形重回帰」における各推計のRコードに説明を追加。
-   第8章「時系列データ操作」と第9章「時系列分析」の冒頭に、時系列データの定義に関する記述を追加。
-   付録「寄与度の計算方法」の「和・差の指標」で、「実例：GDP」の右辺の分子に$\Delta$が記載されていなかった点を修正。「積の指標」で、「実例：経常利益」の変動費の定義を「変動費＝売上原価＋販管費−人件費」から「変動費＝売上原価＋販管費−人件費−減価償却費」に変更し、式にも減価償却費の項を追加。
-   全ての章において、「サンプル数」と記載していた箇所を「サンプルサイズ」に、「サンプル」と記載していた箇所を「データ」に修正。


### 2023年10月9日 マイナーアップデート {-}

-   第2章「Rの設定」の「サンプルデータセット」で、「外部データセット」の「OWIDのCOVID-19データセット」のデータ範囲を2022年12月31日までに限定。
-   第3章「Rの基本的な使用方法」の「ベクトル」に、アトミックベクトルに関する記述を追加。
-   第4章「tidyverseによるデータ操作」の「縦型・横型の変換」で、`tidyr`パッケージの`pivot_longer()`関数と`pivot_wider()`関数で使用するサンプルデータセットを`data_owid`から`iris`に変更し、関数の説明を拡充。
-   第5章「ggplot2によるグラフ作成」の「棒グラフ」で、横並び棒グラフの`position`引数に指定する方法として`position_dodge2()`関数を追加。
-   第5章「ggplot2によるグラフ作成」の「箱ひげ図・ヴァイオリングラフ」で、横並び箱ひげ図に関する記述を追加。
-   第5章「ggplot2によるグラフ作成」の「設定：色」で、色見本の図示に使用するデータセットを`mpg`から自作データセットに変更。
-   第5章「ggplot2によるグラフ作成」の「設定：軸」で、下限・上限の指定方法を`scale_x_*()`、`scale_y_*()`関数ファミリーの`limits`引数から`coord_cartesian()`関数に変更。その他のグラフ作成箇所についても同様に変更。
-   第5章「ggplot2によるグラフ作成」の「実例」で、「実例1：折れ線グラフ」のグラフ作成に使用するデータが誤って`data_owid_line`になっていたため、`data_plot`に修正。

### 2023年9月27日 マイナーアップデート {-}

-   「はじめに」を第1章とし、もとの第1〜8章の章番号を第2〜9章へ1つづつ繰り上げ。
-   第9章「時系列分析」で、数式の右端が表示されていなかった部分を修正。
-   第9章「時系列分析」の「単位根検定（ADF検定）」で、ADF検定フロー自作関数`adf_test_flow()`のプログラムの誤りを修正。フロー6とフロー7の結果が「階差変換し再検定」の場合に`flow_vec`に代入すべき`<- TRUE`が抜けており、その結果、階差変換後のフロー1に判断経路のアスタリスクが記入されないエラーが生じていた。プログラム修正後に第9章の`adf_test_flow()`自作関数使用箇所を再度実行し、判断結果が変化した場合（主に、1次の階差系列で単位根なしと判断する根拠がtrend第2検定からtrend第1検定に変化）、当該箇所を修正。

### 2023年9月22日 メジャーアップデート {.unnumbered}

-   付録「寄与度の計算方法」を追加。

### 2023年6月18日 メジャーアップデート {.unnumbered}

-   第8章「時系列分析」を追加。

### 2023年6月18日 マイナーアップデート {.unnumbered}

-   第1章「Rの設定」の「プロキシサーバーの設定」を「通信関連の設定」に変更し、「SSL設定」を追加。
-   第1章「Rの設定」の「パッケージ」に、`fpp`パッケージを追加。「パッケージ」に「インストール時のエラー」の項目を追加。
-   第1章「Rの設定」の「サンプルデータセット」に、`fpp`パッケージの`usconsumption`データセットを追加。
-   第2章「Rの基本的な使用方法」の「データの書き出し」に、`write.csv()`関数で出力したCSVファイルが文字化けする際の対処方法に関する記述を追加。
-   第7章「時系列データ操作」の「日付型データ関数」に、「日付型データの計算」の項目を追加。

### 2023年4月6日 マイナーアップデート {.unnumbered}

-   参考文献にエンダース（2019）と、村尾（2019）のサポートページを追加。
-   第1章「Rの設定」の「プロキシサーバーの設定」に、`Sys.getenv()`関数を追加。「パッケージ」に、`stringi`パッケージを追加。
-   第2章「Rの基本的な使用方法」の「リスト」に、リスト要素の追加に関する記述を追加。「文字列操作」に、文字列の変換と文字列によるプログラム実行に関する記述を追加。「データの読み込み」と「データの書き出し」を分割し、「データの読み込み」に、複数データの読み込みとExcelの日付値の修正に関する記述を追加。
-   第4章「ggplot2によるグラフ作成」の「凡例」に、`labs()`関数を追加。「グラフの保存」の`height`を9.00から8.50に修正。
-   各章で、参考文献の「西山 他（2019）」を誤って記載していた箇所を修正。

### 2023年3月18日 マイナーアップデート {.unnumbered}

-   参考文献の分類方法を「Rプログラミング」、「統計学・計量経済学」、「時系列データ分析」の3つに再編。
-   参考文献に、北岡 他（2013）、熊本（2022）、仲嶋（2020）、馬場（2018）、松村 他（2022）、宮尾（2006）を追加。
-   第1章「Rの設定」の「パッケージ」に、`ggfortify`、`forecast`、`tseries`パッケージを追加。
-   第1章「Rの設定」の「サンプルデータセット」に、Seatbeltsを追加し、その他のサンプルデータセットの説明内容を一部修正。
-   第2章「Rの基本的な使用方法」の「主要ショートカットキー」に、Macのキーを追加。
-   第2章「Rの基本的な使用方法」の「データの読み込み・書き出し」に、`readr::read_delim()`関数を追加。

### 2023年2月6日 マイナーアップデート {.unnumbered}

-   参考文献にNielsen, A. (2021) 『実践 時系列解析』を追加。
-   第1章「Rの設定」の「パッケージ」に、`lmtest`、`sandwich`、`vars`、`urca`パッケージを追加し、`seasonalview`パッケージを削除。
-   第1章「Rの設定」の「グラフのフォント設定」に、Macの設定を追加。また、Windowsの設定に、`theme_set(theme_light(base_family = "YUGO"))`を追加。以降のすべての章のコードチャンクでWindowsの設定をコメントアウト。
-   第4章「ggplot2によるグラフ作成」で、`family = "YUGO"`を削除。
-   第6章「線形回帰」で、線形回帰モデルの推定に使用する関数を`estimatr::lm_robust()`関数から`stats::lm()`関数と`lmtest::coeftest()`関数の組み合わせに変更。
-   第7章「時系列データ操作」の「トレンド」に、HPフィルタの結果をプロットするコードを追加。

### 2022年10月22日 マイナーアップデート {.unnumbered}

-   複数行にわたる関数のコーディングスタイルを変更。
-   第2章「Rの基本的な使用方法」の「制御構文」に、`next`による処理のスキップを追加。
-   第3章「tidyverseによるデータ操作」の「列の作成・修正」に、文字列型の列を因子型に変換するコードを追加。「集計」から「カウント」を独立させ、要素の種類の数をカウントするコードを追加。「重複処理」に、重複削除のパターンを追加。
-   第5章「探索的データ分析」の「データの中身（記述統計量）」に、文字列型の変数を因子型に変換して要素数を出力するコードを追加。
-   第6章「線形回帰」の「最小2乗法（OLS）」で、最小2乗法の仮定にとp値に関する記述を修正。「Rの単回帰モデル推定」に、実証例4.1の回帰診断プロット作成方法を追加。
-   第6章「線形回帰」の「Rの重回帰モデル推定」で、西村 実証例5.7の説明を追加。
-   第7章「時系列データ操作」に、「時系列データとは」を項目を追加。
-   第7章「時系列データ操作」の「日付型データ関数」に、四半期ベースの時系列インデックスに関する記述を追加。

### 2022年9月7日 マイナーアップデート {.unnumbered}

-   章立てを変更。「時系列データ操作」を「tidyverseによるデータ操作」の後から「線形回帰」の後に移動させ、第1章「Rの設定」、第2章「Rの基本的な使用方法」、第3章「tidyverseによるデータ操作」、第4章「ggplot2によるグラフ作成」、第5章「探索的データ分析」、第6章「線形回帰」、第7章「時系列データ操作」とした。
-   第1章「Rの設定」の「パッケージ」に、`tsibble`、`strucchange`、`nycflights13`の各パッケージを追加。
-   第6章「線形回帰」の「Rの単回帰モデル推定」に、`estimatr::lm_robust()`関数で標準誤差の種類を指定する方法として`HC3`に関する記述、`lm()`関数と`estimatr::lm_robust()`関数の違いに関する記述を追加。
-   第7章「時系列データ操作」に、「ts形式データ」、「ts形式データの変換」、「時系列関数」、「構造変化」の項目を追加。
-   第7章「時系列データ操作」の「トレンド推定」に、線形トレンドと区分線形トレンドに関する記述を追加。

### 2022年7月17日 マイナーアップデート {.unnumbered}

-   第1章「Rの設定」の「サンプルデータセット」に、日本の四半期別GDPを追加。
-   第2章「Rの基本的な使用方法」の「データフレーム」に、`str()`関数を追加。
-   第3章「tidyverseによるデータ操作」に、「行のスライスとサンプリング」の項目を追加。加えて、サンプリングに使用する関数を`dplyr::sample_*()`関数ファミリーから`dplyr::slice_sample()`関数に変更。
-   第3章「tidyverseによるデータ操作」の「行のフィルタ」に、複数列の一括条件指定を追加。
-   第3章「tidyverseによるデータ操作」の「集計」に、要素数のカウントを追加。
-   第5章「ggplot2によるグラフ作成」で、「補助線」、「設定：パネル目盛線」、「設定：凡例」、「設定：タイトル・キャプション」、「設定：フォント・マージン」をセクションとして独立。
-   第5章「ggplot2によるグラフ作成」の「実例」に、折れ線グラフと積み上げ棒グラフを追加。

### 2022年7月9日 マイナーアップデート {.unnumbered}

-   第1章「Rの設定」の「R起動時に実行する設定」に、`.Rprofile`ファイルに関する記述を追加。
-   第2章「Rの基本的な使用方法」に、「第2章の準備」、「文字列操作」、「ファイル操作」の項目を追加。
-   第7章「線形回帰」の「最小2乗法（OLS）」に、HAC標準誤差に関する記述を追加。
-   「変更履歴」を追加。

### 2022年6月26日 ローンチ {.unnumbered}

-   第1章「Rの設定」、第2章「Rの基本的な使用方法」、第3章「tidyverseによるデータ操作」、第4章「時系列データ操作」、第5章「ggplot2によるグラフ作成」、第6章「探索的データ分析」、第7章「線形回帰」を公開。
